<?php

namespace AppBundle\Repository;

/**
 * ContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends \Doctrine\ORM\EntityRepository
{
}
